package pooproject.udesc.poo.calculator;

import java.awt.Color;
import pooproject.udesc.poo.calculator.Services;

/**
 *
 * @author ruan-silva
 */
public class Calculator extends javax.swing.JFrame {
    
    private enum Methods {
        NONE,
        SUM,
        SUBTRACTION,
        MULTIPLICATION,
        DIVISION,
        SPECIAL
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculator.class.getName());
    private Integer number1;
    private Integer number2;
    private String errorMessage;
    private Methods method;
    private Boolean editingFirstNumber;
    // Essa variável será usada para determinar se é o primeiro ou o segundo número que está sendo editado
    // Para salvar os calculos sem precisar de string, dá para pegar o valor anterior, multiplicar por 10 e somar mais o novo número
    // Ex: 5 e bai entrar mais 4 -> 50 x 10 + 4 
    // Adicionar validação de método -> método diferente de NONE então não poderá selecionar um outro método

    public Calculator() {
        initComponents();
        setInitialData();
        
        // Frame settings
        this.setResizable(false);
        this.setTitle("Toy Story Calculator");
        
        // Added custom modifies to scape of NetBeans UI builder fixes.
        CalculatorImageBody.setOpaque(false);
        CalculatorImageBody.setBackground(new Color(242, 242, 242, 190));
    }
    
    // Calculator methods
    private void setInitialData() {
        this.number1 = null;
        this.number2 = null;
        this.errorMessage = null;
        this.method = Methods.NONE;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CalculatorImageBody = new javax.swing.JPanel();
        CalculatorBody = new javax.swing.JPanel();
        CalculatorWindow = new javax.swing.JPanel();
        ClearButton = new javax.swing.JButton();
        ButtonNumberOne = new javax.swing.JButton();
        ButtonNumberTwo = new javax.swing.JButton();
        ButtonNumberThree = new javax.swing.JButton();
        ButtonNumberFour = new javax.swing.JButton();
        ButtonNumberFive = new javax.swing.JButton();
        ButtonNumberSix = new javax.swing.JButton();
        ButtonNumberSeven = new javax.swing.JButton();
        ButtonNumberEight = new javax.swing.JButton();
        ButtonNumberNine = new javax.swing.JButton();
        ButtonNumberZero = new javax.swing.JButton();
        SpecialButton = new javax.swing.JButton();
        EqualsButton = new javax.swing.JButton();
        SumButton = new javax.swing.JButton();
        SubtractionButton = new javax.swing.JButton();
        MultiplicationButton = new javax.swing.JButton();
        DivisionButton = new javax.swing.JButton();
        BackgoundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CalculatorImageBody.setBackground(new java.awt.Color(241, 247, 251));
        CalculatorImageBody.setLayout(null);

        CalculatorBody.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        CalculatorWindow.setBackground(new java.awt.Color(204, 255, 255));
        CalculatorWindow.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        javax.swing.GroupLayout CalculatorWindowLayout = new javax.swing.GroupLayout(CalculatorWindow);
        CalculatorWindow.setLayout(CalculatorWindowLayout);
        CalculatorWindowLayout.setHorizontalGroup(
            CalculatorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        CalculatorWindowLayout.setVerticalGroup(
            CalculatorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        ClearButton.setBackground(new java.awt.Color(0, 82, 232));
        ClearButton.setForeground(new java.awt.Color(255, 255, 255));
        ClearButton.setText("Clear");
        ClearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClearButton.addActionListener();

        ButtonNumberOne.setBackground(new java.awt.Color(204, 204, 204));
        ButtonNumberOne.setText("1");
        ButtonNumberOne.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ButtonNumberOne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNumberOne.addActionListener();

        ButtonNumberTwo.setBackground(new java.awt.Color(204, 204, 204));
        ButtonNumberTwo.setText("2");
        ButtonNumberTwo.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ButtonNumberTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNumberTwo.addActionListener();

        ButtonNumberThree.setBackground(new java.awt.Color(204, 204, 204));
        ButtonNumberThree.setText("3");
        ButtonNumberThree.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ButtonNumberThree.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNumberThree.addActionListener();

        ButtonNumberFour.setBackground(new java.awt.Color(204, 204, 204));
        ButtonNumberFour.setText("4");
        ButtonNumberFour.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ButtonNumberFour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNumberFour.addActionListener();

        ButtonNumberFive.setBackground(new java.awt.Color(204, 204, 204));
        ButtonNumberFive.setText("5");
        ButtonNumberFive.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ButtonNumberFive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNumberFive.addActionListener();

        ButtonNumberSix.setBackground(new java.awt.Color(204, 204, 204));
        ButtonNumberSix.setText("6");
        ButtonNumberSix.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ButtonNumberSix.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNumberSix.addActionListener();

        ButtonNumberSeven.setBackground(new java.awt.Color(204, 204, 204));
        ButtonNumberSeven.setText("7");
        ButtonNumberSeven.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ButtonNumberSeven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNumberSeven.addActionListener();

        ButtonNumberEight.setBackground(new java.awt.Color(204, 204, 204));
        ButtonNumberEight.setText("8");
        ButtonNumberEight.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ButtonNumberEight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNumberEight.addActionListener();

        ButtonNumberNine.setBackground(new java.awt.Color(204, 204, 204));
        ButtonNumberNine.setText("9");
        ButtonNumberNine.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ButtonNumberNine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNumberNine.addActionListener();

        ButtonNumberZero.setBackground(new java.awt.Color(204, 204, 204));
        ButtonNumberZero.setText("0");
        ButtonNumberZero.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ButtonNumberZero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonNumberZero.addActionListener();

        SpecialButton.setBackground(new java.awt.Color(204, 204, 204));
        SpecialButton.setText("?");
        SpecialButton.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        SpecialButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SpecialButton.addActionListener();

        EqualsButton.setBackground(new java.awt.Color(204, 204, 204));
        EqualsButton.setText("=");
        EqualsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        EqualsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SumButton.setBackground(new java.awt.Color(204, 204, 204));
        SumButton.setText("+");
        SumButton.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        SumButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SumButton.addActionListener();

        SubtractionButton.setBackground(new java.awt.Color(204, 204, 204));
        SubtractionButton.setText("-");
        SubtractionButton.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        SubtractionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubtractionButton.addActionListener();

        MultiplicationButton.setBackground(new java.awt.Color(204, 204, 204));
        MultiplicationButton.setText("*");
        MultiplicationButton.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        MultiplicationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MultiplicationButton.addActionListener();

        DivisionButton.setBackground(new java.awt.Color(204, 204, 204));
        DivisionButton.setText("/");
        DivisionButton.setBorder(javax.swing.BorderFactory.createBevelBorder(null, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        DivisionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DivisionButton.addActionListener();

        javax.swing.GroupLayout CalculatorBodyLayout = new javax.swing.GroupLayout(CalculatorBody);
        CalculatorBody.setLayout(CalculatorBodyLayout);
        CalculatorBodyLayout.setHorizontalGroup(
            CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculatorBodyLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CalculatorWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CalculatorBodyLayout.createSequentialGroup()
                        .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonNumberTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CalculatorBodyLayout.createSequentialGroup()
                                .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SpecialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonNumberFour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonNumberOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonNumberSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonNumberFive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonNumberEight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonNumberZero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CalculatorBodyLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButtonNumberThree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonNumberSix, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonNumberNine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SumButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SubtractionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MultiplicationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DivisionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculatorBodyLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        CalculatorBodyLayout.setVerticalGroup(
            CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculatorBodyLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(CalculatorWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatorBodyLayout.createSequentialGroup()
                        .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonNumberOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonNumberTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonNumberThree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonNumberFour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonNumberFive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonNumberSix, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SubtractionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculatorBodyLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ButtonNumberSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(78, 78, 78))
                        .addGroup(CalculatorBodyLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ButtonNumberNine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonNumberEight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(CalculatorBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ButtonNumberZero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SpecialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CalculatorBodyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(MultiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DivisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        CalculatorImageBody.add(CalculatorBody);
        CalculatorBody.setBounds(30, 40, 414, 605);
        CalculatorBody.getAccessibleContext().setAccessibleName("");

        BackgoundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/toystory.jpg"))); // NOI18N
        CalculatorImageBody.add(BackgoundImage);
        BackgoundImage.setBounds(-4, -2, 490, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalculatorImageBody, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalculatorImageBody, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        this.setInitialData();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void ButtonNumberThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumberThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNumberThreeActionPerformed

    private void SumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SumButtonActionPerformed

    private void SubtractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubtractionButtonActionPerformed

    private void MultiplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultiplicationButtonActionPerformed

    private void DivisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DivisionButtonActionPerformed

    private void SpecialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecialButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialButtonActionPerformed

    private void ButtonNumberOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumberOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNumberOneActionPerformed

    private void ButtonNumberTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumberTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNumberTwoActionPerformed

    private void ButtonNumberFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumberFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNumberFourActionPerformed

    private void ButtonNumberFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumberFiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNumberFiveActionPerformed

    private void ButtonNumberSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumberSixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNumberSixActionPerformed

    private void ButtonNumberSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumberSevenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNumberSevenActionPerformed

    private void ButtonNumberEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumberEightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNumberEightActionPerformed

    private void ButtonNumberNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumberNineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNumberNineActionPerformed

    private void ButtonNumberZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumberZeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNumberZeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgoundImage;
    private javax.swing.JButton ButtonNumberEight;
    private javax.swing.JButton ButtonNumberFive;
    private javax.swing.JButton ButtonNumberFour;
    private javax.swing.JButton ButtonNumberNine;
    private javax.swing.JButton ButtonNumberOne;
    private javax.swing.JButton ButtonNumberSeven;
    private javax.swing.JButton ButtonNumberSix;
    private javax.swing.JButton ButtonNumberThree;
    private javax.swing.JButton ButtonNumberTwo;
    private javax.swing.JButton ButtonNumberZero;
    private javax.swing.JPanel CalculatorBody;
    private javax.swing.JPanel CalculatorImageBody;
    private javax.swing.JPanel CalculatorWindow;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DivisionButton;
    private javax.swing.JButton EqualsButton;
    private javax.swing.JButton MultiplicationButton;
    private javax.swing.JButton SpecialButton;
    private javax.swing.JButton SubtractionButton;
    private javax.swing.JButton SumButton;
    // End of variables declaration//GEN-END:variables
}
